[package]
name = "bridge"
version = "0.1.0"
authors = ["Ryan Chipman <ryan@ryanchipman.com>"]

[dependencies]
rand = "0.6"
diesel = { version = "1.3.3", features = ["sqlite"] }
diesel_migrations = { version = "1.3", features = ["sqlite"] }
clap = "2.32"